import type { DashboardArea } from "@/types";

export const dashboardNavigation: Record<DashboardArea, { label: string; href: string }[]> = {
  member: [
    { label: "Dashboard", href: "/member/dashboard" },
    { label: "Opportunities", href: "/member/opportunities" },
    { label: "My Participations", href: "/member/participations" },
    { label: "Active Projects", href: "/member/projects/active" },
    { label: "Completed Projects", href: "/member/projects/completed" },
    { label: "Distributions", href: "/member/distributions" },
    { label: "Announcements", href: "/member/announcements" },
    { label: "Notifications", href: "/member/notifications" },
    { label: "Media Gallery", href: "/member/media" },
    { label: "FAQ", href: "/member/faq" },
    { label: "Risk Disclosure", href: "/member/risk-disclosure" },
    { label: "Profile", href: "/member/profile" },
    { label: "Settings", href: "/member/settings" },
    { label: "Security", href: "/member/security" },
  ],
  advisor: [
    { label: "Dashboard", href: "/advisor/dashboard" },
    { label: "My Members", href: "/advisor/members" },
    { label: "Cases", href: "/advisor/cases" },
    { label: "Follow Up", href: "/advisor/follow-up" },
    { label: "Notes", href: "/advisor/notes" },
    { label: "Recommendations", href: "/advisor/recommendations" },
    { label: "Reports", href: "/advisor/reports" },
  ],
  admin: [
    { label: "Dashboard", href: "/admin/dashboard" },
    { label: "Members", href: "/admin/members" },
    { label: "eKYC", href: "/admin/ekyc" },
    { label: "Assets", href: "/admin/assets" },
    { label: "Contributions", href: "/admin/contributions" },
    { label: "Payments", href: "/admin/payments" },
    { label: "Distributions", href: "/admin/distributions" },
    { label: "Commissions", href: "/admin/commissions" },
    { label: "Reports", href: "/admin/reports" },
    { label: "Analytics", href: "/admin/analytics" },
    { label: "Corporate Content", href: "/admin/corporate-content" },
    { label: "Activity Logs", href: "/admin/activity-logs" },
    { label: "Settings", href: "/admin/settings" },
  ],
};
